# Based on the template for pyright(LSP):
# - https://microsoft.github.io/pyright/#/getting-started
# - https://microsoft.github.io/pyright/#/configuration

{
  "include": [
    "orders",
    "products",
    "test",
    "gateapi",
    "gateway",
  ],

  "exclude": [
    "**/__pycache__",
    # From template
    # "**/node_modules",
    # "src/experimental",
    # "src/typestubs"
  ],

  "ignore": [
    # From template
    # "src/oldstuff"
  ],

  "defineConstant": {
    "DEBUG": true
  },

  "stubPath": "src/stubs",
  "venv": "env367",

  "reportMissingImports": true,
  "reportMissingTypeStubs": true, # default: false

  "pythonVersion": "3.7.12",
  "pythonPlatform": "Linux",

  "executionEnvironments": [
    {
      "root": "./" # default: "src/"
    }
    # {
    #   "root": "src/web",
    #   "pythonVersion": "3.7.12",
    #   "pythonPlatform": "Linux", # default: Windows
    #   "extraPaths": [
    #     # From template
    #     # "src/service_libs"
    #   ]
    # },
    # {
    #   "root": "orders",
    #   "pythonVersion": "3.7.12",
    #   "extraPaths": [
    #     "orders/alembic",
    #     "orders/orders",
    #     "orders/test"
    #   ]
    # },
    # {
    #   "root": "test",
    #   "extraPaths": [
    #     # "src/tests/e2e",
    #     # "src/sdk"
    #   ]
    # },
  ]
}
